DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS WALLETS;
 
CREATE TABLE USERS (
  	id INT AUTO_INCREMENT  PRIMARY KEY,
	first_name VARCHAR(250) NOT NULL,
	last_name VARCHAR(250) NOT NULL,
	email VARCHAR(250) DEFAULT NULL,
	company VARCHAR(250) DEFAULT 'Pagantis',
	address VARCHAR(250) DEFAULT NULL, 
	city VARCHAR(250) DEFAULT NULL,
	country VARCHAR(230) DEFAULT NULL,
	ZIP_CODE VARCHAR(230) DEFAULT NULL,
	USER_NAME VARCHAR(250) DEFAULT NULL,
	password VARCHAR(250) DEFAULT NULL);

CREATE TABLE WALLETS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name  VARCHAR(250) NOT NULL,
  balance double DEFAULT 0.00,	
	address VARCHAR(350)  NOT NULL,
	private_key VARCHAR(350) NOT NULL,
	user_id INT  NOT NULL);



 
